openapi: 3.0.0
info:
  title: Country API
  description: API to retrieve information about countries
  version: 1.0.0
paths:
  /countries:
    get:
      summary: Retrieve all countries
      responses:
        '200':
          description: A list of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  /countries/{name}:
    get:
      summary: Retrieve details about a specific country
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the country
          schema:
            type: string
      responses:
        '200':
          description: Details of the specified country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetails'
        '404':
          description: Country not found
components:
  schemas:
    Country:
      type: object
      properties:
        name:
          type: string
        flag:
          type: string
    CountryDetails:
      type: object
      properties:
        name:
          type: string
        population:
          type: integer